Repository drink-this/drink-this-backend, pull requests merged in 2021-08, with the labels that each got.

#14 Cocktail details new
  Gemfile.lock
  app/controllers/api/v1/cocktails/rating_controller.rb
  app/controllers/api/v1/cocktails_controller.rb
  app/facades/cocktail_facade.rb
  app/models/cocktail.rb
  app/models/rating.rb
  app/models/user.rb
  app/poros/cocktail_details.rb
  app/serializers/cocktail_details_serializer.rb
  app/serializers/rating_serializer.rb
  app/services/cocktail_service.rb
  app/services/recommendation_service.rb
  config/initializers/serializer.rb
  config/routes.rb
  spec/facades/cocktail_facade_spec.rb
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_json_with_cocktail_details.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_rating_if_present.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_get_cocktail_details/returns_cocktail_data.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_of_cocktail_details_via_get_request.yml
  spec/models/cocktail_spec.rb
  spec/models/rating_spec.rb
  spec/models/user_spec.rb
  spec/poros/cocktail_details_spec.rb
  spec/rails_helper.rb
  spec/recommendation/engine_spec.rb
  spec/requests/api/v1/cocktail/cocktail_request_spec.rb
  spec/requests/api/v1/cocktail/rating_request_spec.rb
  spec/services/cocktail_service_spec.rb
Labels: Backend, enhancement

#16 Cocktail search
  app/controllers/api/v1/cocktails/search_controller.rb
  app/controllers/api/v1/cocktails_controller.rb
  app/facades/cocktail_facade.rb
  app/models/rating.rb
  app/serializers/cocktail_search_serializer.rb
  app/services/cocktail_service.rb
  config/routes.rb
  spec/facades/cocktail_facade_spec.rb
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_json_with_list_of_cocktails_by_query.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_cocktails/returns_search_results.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/send_json_of_cocktail_list_via_get_request.yml
  spec/models/rating_spec.rb
  spec/requests/api/v1/cocktail/cocktail_search_spec.rb
  spec/services/cocktail_service_spec.rb
Labels: Backend, enhancement

#17 Oauth
  Gemfile
  Gemfile.lock
  app/controllers/authentication_controller.rb
  app/models/user.rb
  app/services/google_service.rb
  config/application.rb
  config/initializers/cors.rb
  config/routes.rb
  db/migrate/20210728013735_create_users.rb
  db/migrate/20210728155223_add_google_token_to_users.rb
  db/schema.rb
  spec/api/v1/authentication/get_token_auth_spec.rb
  spec/factories/users.rb
Labels: Backend, enhancement

#18 migration for removing password_digest, change validation to reflect
  db/migrate/20210803003329_remove_password_digest_from_users.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: Backend

#19 Recommendation Endpoint
  Gemfile.lock
  app/controllers/api/v1/recommendations_controller.rb
  app/facades/cocktail_facade.rb
  app/modules/dataframeable.rb
  app/services/recommendation_service.rb
  config/routes.rb
  db/migrate/20210728013735_create_users.rb
  spec/facades/cocktail_facade_spec.rb
  spec/factories/users.rb
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation/user_is_logged_in/returns_a_recommendation_based_on_other_user_data.yml
  spec/models/user_spec.rb
  spec/recommendation/engine_spec.rb
  spec/requests/api/v1/cocktails/details_spec.rb
  spec/requests/api/v1/cocktails/rating_request_spec.rb
  spec/requests/api/v1/cocktails/recommendation_request_spec.rb
  spec/requests/api/v1/cocktails/search_spec.rb
Labels: Backend, recommendation engine

#20 Sad paths
  Gemfile.lock
  app/controllers/api/v1/authorization_controller.rb
  app/controllers/api/v1/cocktails/search_controller.rb
  app/controllers/api/v1/cocktails_controller.rb
  app/facades/cocktail_facade.rb
  app/models/user.rb
  app/serializers/cocktail_search_serializer.rb
  db/migrate/20210728013735_create_users.rb
  db/schema.rb
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/_sad_path_send_json_error_when_there_is_an_incorrect_cocktail_id.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_error_when_no_params_provided.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_error_when_no_params_with_user_id.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_error_when_there_is_an_incorrect_cocktail_id.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_blank_search_query.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_incorrect_search_query.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_search_query_is_gibberish.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_search_query_with_no_results.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_when_user_is_incorrect.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_when_user_is_not_in_params.yml
  spec/requests/api/v1/cocktails/details_spec.rb
  spec/requests/api/v1/cocktails/search_spec.rb
Labels: Backend, documentation, enhancement

#21 Add path for first recommendation user
  .rubocop.yml
  app/controllers/api/v1/cocktails/rating_controller.rb
  app/controllers/api/v1/recommendations_controller.rb
  app/controllers/authentication_controller.rb
  app/facades/cocktail_facade.rb
  app/models/rating.rb
  app/models/user.rb
  app/services/cocktail_service.rb
  app/services/google_service.rb
  app/services/recommendation_service.rb
  spec/facades/cocktail_facade_spec.rb
  spec/fixtures/random_cocktail.json
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_details/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_random_cocktail/returns_data_for_a_random_cocktail.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation/user_is_logged_in_and_other_users_are_present/returns_a_recommendation_based_on_other_user_data.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation_with_randomness/provides_a_random_cocktail_if_no_similar_not_identical_users_exist.yml
  spec/requests/api/v1/cocktails/recommendation_request_spec.rb
  spec/services/cocktail_service_spec.rb
Labels: Backend, recommendation engine

#23 Update VCR Cassettes
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_json_with_cocktail_details.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_rating_if_present.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_details/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_json_with_list_of_cocktails_by_query.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_get_cocktail_details/returns_cocktail_data.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_random_cocktail/returns_data_for_a_random_cocktail.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_cocktails/returns_search_results.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/_sad_path_send_json_error_when_there_is_an_incorrect_cocktail_id.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_error_when_no_params_provided.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_error_when_no_params_with_user_id.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_error_when_there_is_an_incorrect_cocktail_id.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_of_cocktail_details_via_get_request.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_blank_search_query.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_incorrect_search_query.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_search_query_is_gibberish.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_search_query_with_no_results.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_when_user_is_incorrect.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_when_user_is_not_in_params.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/send_json_of_cocktail_list_via_get_request.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation/user_is_logged_in/returns_a_recommendation_based_on_other_user_data.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation/user_is_logged_in_and_other_users_are_present/returns_a_recommendation_based_on_other_user_data.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation_with_randomness/provides_a_random_cocktail_if_no_similar_not_identical_users_exist.yml
  spec/services/cocktail_service_spec.rb
Labels: Backend

#24 Yelp search
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/cocktails/search_controller.rb
  app/controllers/api/v1/cocktails_controller.rb
  app/controllers/api/v1/yelp_search_controller.rb
  app/facades/cocktail_facade.rb
  app/facades/yelp_facade.rb
  app/poros/business.rb
  app/serializers/yelp_serializer.rb
  app/services/yelp_service.rb
  config/routes.rb
  spec/facades/yelp_facade_spec.rb
  spec/fixtures/vcr_cassettes/YelpService/_get_businesses/returns_search_results.yml
  spec/fixtures/vcr_cassettes/YelpService/_search_nearby/returns_array_of_business_poros.yml
  spec/fixtures/vcr_cassettes/Yelp_Cocktail_Search_API/show_response_endpoint/sends_json_of_list_of_businesses.yml
  spec/poros/business_spec.rb
  spec/requests/api/v1/yelp/yelp_cocktail_search_spec.rb
  spec/services/yelp_service_spec.rb
Labels: Backend, enhancement

#25 Update ratings endpoint to create cocktail if not already in DB
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/authorization_controller.rb
  app/controllers/api/v1/cocktails/rating_controller.rb
  app/controllers/api/v1/cocktails/search_controller.rb
  app/controllers/api/v1/cocktails_controller.rb
  app/facades/cocktail_facade.rb
  app/models/rating.rb
  app/modules/dataframeable.rb
  app/services/cocktail_service.rb
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_rating_if_present.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_details/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_json_with_list_of_cocktails_by_query.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_blank_search_query.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/creates_the_cocktail_in_the_database_and_adds_the_rating_as_well.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/returns_error_if_cocktail_not_found_by_the_API.yml
  spec/models/rating_spec.rb
  spec/requests/api/v1/cocktails/details_spec.rb
  spec/requests/api/v1/cocktails/rating_request_spec.rb
  spec/requests/api/v1/cocktails/search_spec.rb
Labels: Backend, documentation, enhancement

#29 Update heroku config vars and gemfile for compatibility
  .circleci/config.yml
  Gemfile
  Gemfile.lock
Labels: Backend

#31 Dashboard
  app/controllers/api/v1/dashboard_controller.rb
  app/models/cocktail.rb
  app/serializers/cocktail_dashboard_serializer.rb
  config/routes.rb
  spec/api/v1/authentication/get_token_auth_spec.rb
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_rating_if_present.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_details/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_json_with_list_of_cocktails_by_query.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_get_cocktail_details/returns_cocktail_data.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_random_cocktail/returns_data_for_a_random_cocktail.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_cocktails/returns_search_results.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/_sad_path_send_json_error_when_there_is_an_incorrect_cocktail_id.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_of_cocktail_details_via_get_request.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_blank_search_query.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_search_query_is_gibberish.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/send_json_of_cocktail_list_via_get_request.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/creates_the_cocktail_in_the_database_and_adds_the_rating_as_well.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/returns_error_if_cocktail_not_found_by_the_API.yml
  spec/fixtures/vcr_cassettes/YelpService/_get_businesses/returns_search_results.yml
  spec/fixtures/vcr_cassettes/YelpService/_search_nearby/returns_array_of_business_poros.yml
  spec/fixtures/vcr_cassettes/Yelp_Cocktail_Search_API/show_response_endpoint/sends_json_of_list_of_businesses.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation/user_is_logged_in_and_other_users_are_present/returns_a_recommendation_based_on_other_user_data.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation_with_randomness/provides_a_random_cocktail_if_no_similar_not_identical_users_exist.yml
  spec/models/cocktail_spec.rb
  spec/requests/api/v1/cocktails/dashboard_spec.rb
Labels: Backend, enhancement

#32 Fix future and copy warning
  app/services/recommendation_service.rb
Labels: Backend, documentation

#34 Update config for FE testing
  app/controllers/authentication_controller.rb
  config/initializers/cors.rb
Labels: Backend

#35 Update dashboard cocktail methods
  app/controllers/api/v1/dashboard_controller.rb
  app/models/cocktail.rb
  app/serializers/cocktail_dashboard_serializer.rb
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_rating_if_present.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_details/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_json_with_list_of_cocktails_by_query.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_get_cocktail_details/returns_cocktail_data.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_random_cocktail/returns_data_for_a_random_cocktail.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_cocktails/returns_search_results.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/_sad_path_send_json_error_when_there_is_an_incorrect_cocktail_id.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_of_cocktail_details_via_get_request.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_search_query_is_gibberish.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/send_json_of_cocktail_list_via_get_request.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/creates_the_cocktail_in_the_database_and_adds_the_rating_as_well.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/returns_error_if_cocktail_not_found_by_the_API.yml
  spec/fixtures/vcr_cassettes/YelpService/_get_businesses/returns_search_results.yml
  spec/fixtures/vcr_cassettes/YelpService/_search_nearby/returns_array_of_business_poros.yml
  spec/fixtures/vcr_cassettes/Yelp_Cocktail_Search_API/show_response_endpoint/sends_json_of_list_of_businesses.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation/user_is_logged_in_and_other_users_are_present/returns_a_recommendation_based_on_other_user_data.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation_with_randomness/provides_a_random_cocktail_if_no_similar_not_identical_users_exist.yml
  spec/models/cocktail_spec.rb
  spec/requests/api/v1/cocktails/dashboard_spec.rb
Labels: Backend

#37 Test authentication controller
  app/controllers/authentication_controller.rb
  app/facades/cocktail_facade.rb
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_rating_if_present.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_details/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_json_with_list_of_cocktails_by_query.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_get_cocktail_details/returns_cocktail_data.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_random_cocktail/returns_data_for_a_random_cocktail.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_cocktails/returns_search_results.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/_sad_path_send_json_error_when_there_is_an_incorrect_cocktail_id.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_of_cocktail_details_via_get_request.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_search_query_is_gibberish.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/send_json_of_cocktail_list_via_get_request.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/creates_the_cocktail_in_the_database_and_adds_the_rating_as_well.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/returns_error_if_cocktail_not_found_by_the_API.yml
  spec/fixtures/vcr_cassettes/YelpService/_get_businesses/returns_search_results.yml
  spec/fixtures/vcr_cassettes/YelpService/_search_nearby/returns_array_of_business_poros.yml
  spec/fixtures/vcr_cassettes/Yelp_Cocktail_Search_API/show_response_endpoint/sends_json_of_list_of_businesses.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation/user_is_logged_in_and_other_users_are_present/returns_a_recommendation_based_on_other_user_data.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation_with_randomness/provides_a_random_cocktail_if_no_similar_not_identical_users_exist.yml
  spec/requests/authentication_spec.rb
  spec/services/yelp_service_spec.rb
Labels: Backend

#38 Make it pretty.
  app/models/rating.rb
Labels: Backend

#40 Update cocktail.rb
  app/models/cocktail.rb
  spec/models/cocktail_spec.rb
Labels: bug, Backend

#50 added route to get rated cocktails for a user
  app/controllers/api/v1/cocktails_controller.rb
  app/models/user.rb
  app/serializers/rated_cocktails_serializer.rb
  config/routes.rb
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_rating_if_present.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_details/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_json_with_list_of_cocktails_by_query.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_search_results_by_name_and_ingredient.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_search_results_by_name_ingredient_does_not_exist_.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_search_results_by_name_name_does_not_exist_.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_get_cocktail_details/returns_an_empty_array_if_no_cocktail_exists.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_get_cocktail_details/returns_cocktail_data.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_random_cocktail/returns_data_for_a_random_cocktail.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_by_ingredient/returns_nil_if_no_results_are_found.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_by_ingredient/returns_search_results.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_by_name/returns_nil_if_no_results_are_found.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_by_name/returns_search_results.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/_sad_path_send_json_error_when_there_is_an_incorrect_cocktail_id.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_of_cocktail_details_via_get_request.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_search_query_is_gibberish.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/send_json_of_cocktail_list_via_get_request.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/creates_the_cocktail_in_the_database_and_adds_the_rating_as_well.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/returns_error_if_cocktail_not_found_by_the_API.yml
  spec/fixtures/vcr_cassettes/YelpService/_get_businesses/returns_search_results.yml
  spec/fixtures/vcr_cassettes/YelpService/_search_nearby/returns_array_of_business_poros.yml
  spec/fixtures/vcr_cassettes/Yelp_Cocktail_Search_API/show_response_endpoint/sends_json_of_list_of_businesses.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation/user_is_logged_in_and_other_users_are_present/returns_a_recommendation_based_on_other_user_data.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation_with_randomness/provides_a_random_cocktail_if_no_similar_not_identical_users_exist.yml
  spec/requests/api/v1/cocktails/rated_cocktails_spec.rb
  spec/services/yelp_service_spec.rb
Labels: enhancement, Backend

#54 Homepage dupes.fix
  app/models/cocktail.rb
  app/poros/homepage.rb
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_by_glass/returns_an_empty_array_if_no_cocktails_for_glass_type.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_by_glass/returns_cocktails_for_glass_type_and_ratings.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_cocktail/returns_rating_if_present.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_details/returns_json_with_cocktail_details_and_rating.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/does_not_return_duplicate_cocktails.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_json_with_list_of_cocktails_by_query.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_search_results_by_name_and_ingredient.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_search_results_by_name_ingredient_does_not_exist_.yml
  spec/fixtures/vcr_cassettes/CocktailFacade/_retrieve_search_results/returns_search_results_by_name_name_does_not_exist_.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_get_cocktail_details/returns_an_empty_array_if_no_cocktail_exists.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_get_cocktail_details/returns_cocktail_data.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_random_cocktail/returns_data_for_a_random_cocktail.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_by_glass/returns_nil_if_no_results_are_found.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_by_glass/returns_search_results_for_given_glass_type.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_by_ingredient/returns_nil_if_no_results_are_found.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_by_ingredient/returns_search_results.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_by_name/returns_nil_if_no_results_are_found.yml
  spec/fixtures/vcr_cassettes/CocktailService/class_methods/_search_by_name/returns_search_results.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/_sad_path_send_json_error_when_there_is_an_incorrect_cocktail_id.yml
  spec/fixtures/vcr_cassettes/Cocktail_Details_API/show_response_endpoint/send_json_of_cocktail_details_via_get_request.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/_sad_path_sends_error_message_when_search_query_is_gibberish.yml
  spec/fixtures/vcr_cassettes/Cocktail_Search_API/show_response_endpoint/send_json_of_cocktail_list_via_get_request.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/creates_the_cocktail_in_the_database_and_adds_the_rating_as_well.yml
  spec/fixtures/vcr_cassettes/Rating_API/show_response_endpoint/the_cocktail_does_not_yet_exist_in_our_database/returns_error_if_cocktail_not_found_by_the_API.yml
  spec/fixtures/vcr_cassettes/YelpService/_get_businesses/returns_search_results.yml
  spec/fixtures/vcr_cassettes/YelpService/_search_nearby/returns_array_of_business_poros.yml
  spec/fixtures/vcr_cassettes/Yelp_Cocktail_Search_API/show_response_endpoint/sends_json_of_list_of_businesses.yml
  spec/fixtures/vcr_cassettes/homepage_endpoint.yml
  spec/fixtures/vcr_cassettes/homepage_poro.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation/user_is_logged_in_and_other_users_are_present/returns_a_recommendation_based_on_other_user_data.yml
  spec/fixtures/vcr_cassettes/recommendation/GET_/recommendation_with_randomness/provides_a_random_cocktail_if_no_similar_not_identical_users_exist.yml
  spec/models/cocktail_spec.rb
  spec/services/yelp_service_spec.rb
Labels: bug, documentation, Backend
